builds:
  - binary: gothub
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64

archive:
  files:
    - LICENSE
    - README.md
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: x86_64
    386: x86
    darwin: macos
  wrap_in_directory: true
